wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.17.3
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1720027859
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      4: 3.12.3
      5: 0.17.3
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 0.001
batch_size:
  desc: null
  value: 32
num_epochs:
  desc: null
  value: 25
sequence_length:
  desc: null
  value: 1
